[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
remappings = [
    "@chainlink=lib/chainlink-brownie-contracts/contracts",
    "@solmate=lib/solmate/src",
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
private_keys = ["${PRIVATE_KEY}"]

[fuzz]
runs = 256
